FROM node:14.8.0-alpine as build
WORKDIR /app
ENV NODE_ENV production
COPY package.json ./
RUN npm i --silent
COPY . ./
RUN npm install tailwindcss postcss-cli autoprefixer@9.8.6 -D -g
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]